% =========================================================================
% step2_mdf_v3.m MDF per repetition on the fatigue block
% =========================================================================
% Reads the .mat file generated by step1_preprocess.m (pre_[name].mat).
% The fatigue block is already segmented and filtered no reloading
% or re-selection needed.
%
% Method: AR order 3, Burg's method (pburg), onset detection by percentile.
%
% Output results/mdf3_[name].mat:
%   .mdf_reps     [n_reps x 7]  MDF per repetition and channel (Hz)
%   .t_rep        [n_reps x 1]  centre time of each rep (s, relative to block)
%   .slopes       [1 x 7]       linear regression slope (Hz/s)
%   .r2           [1 x 7]       coefficient of determination
%   .pct_thr      percentile used as onset threshold
%   .thr          threshold value in uV
%   .muscle_names
%   .n_reps
%   .fname
%
% Compatibility: MATLAB R2016b+
% =========================================================================

clear; clc;

% -- Parameters -------------------------------------------------------------
Fs       = 2148;
low_cut  = 20;
high_cut = 450;

muscle_names = {'AD','LD','PD','UT','BB','TB','ECR'};
n_muscles    = numel(muscle_names);

% -- Load .mat from step1_preprocess ----------------------------------------
[fname_mat, fpath_mat] = uigetfile('*.mat', 'Select pre_[name].mat (from step1_preprocess)');
if isequal(fname_mat, 0), error('No file selected.'); end

fprintf('Loading %s ...\n', fname_mat);
S = load(fullfile(fpath_mat, fname_mat));

% Check that the fatigue block is present
if ~isfield(S, 'fatigue')
    error('The .mat does not contain the "fatigue" field. Make sure to use the output of step1_preprocess.m');
end

t_fat  = S.fatigue.t;
bp_fat = S.fatigue.filtered;   % already filtered [M x 7]
fprintf('  Subject: %s | Condition: %s\n', S.fname, S.condition);
fprintf('  Fatigue block: %.1f - %.1f s (%.1f s)\n', ...
        t_fat(1), t_fat(end), t_fat(end)-t_fat(1));

% -- Envelopes of the fatigue block -> choose reference channel -------------
env_fat = zeros(size(bp_fat));
[b_lp, a_lp] = butter(4, 8/(Fs/2), 'low');
for ch = 1:n_muscles
    env_fat(:,ch) = filtfilt(b_lp, a_lp, abs(bp_fat(:,ch)));
end

figure('Name', 'Fatigue block envelopes select reference channel');
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    plot(t_fat, env_fat(:,ch)*1e6, 'b', 'LineWidth', 0.8);
    ylabel('uV'); title(muscle_names{ch}); grid on;
end
xlabel('Time (s)');
sgtitle('Fatigue block envelopes which channel to use as reference?');

ref_muscle = input('Enter reference channel number (1=AD, 2=LD, 3=PD, 4=UT, 5=BB, 6=TB, 7=ECR): ');

% -- Sliding window RMS of the reference channel ----------------------------
win_rms = round(0.5 * Fs);
rms_ref = sqrt(movmean(bp_fat(:, ref_muscle).^2, win_rms)) * 1e6;

figure('Name', ['Sliding RMS ' muscle_names{ref_muscle}]);
plot(t_fat, rms_ref, 'b', 'LineWidth', 1);
xlabel('Time (s)'); ylabel('uV');
title(['Sliding window RMS (0.5s) ' muscle_names{ref_muscle}]);
grid on;

% -- Onset detection by percentile threshold --------------------------------
% Default percentile 25: in the 1 rep/4s protocol (~2.5s active, ~1.5s rest)
% valleys occupy ~35-40% of the time -> pct 25 falls in the valley distribution.
pct_thr = 25;
thr     = prctile(rms_ref, pct_thr);

while true
    above   = rms_ref > thr;
    d_above = diff([0; above; 0]);
    onset_idx  = find(d_above ==  1);
    offset_idx = find(d_above == -1);

    min_dur    = round(1.0 * Fs);
    valid      = (offset_idx - onset_idx) >= min_dur;
    onset_idx  = onset_idx(valid);
    offset_idx = offset_idx(valid);
    n_reps     = numel(onset_idx);

    fprintf('\n--- Repetition detection ---\n');
    fprintf('  Threshold percentile: %d  (%.1f uV) | Repetitions: %d\n', pct_thr, thr, n_reps);
    for k = 1:n_reps
        dur_k = (offset_idx(k) - onset_idx(k)) / Fs;
        fprintf('  Rep %2d: %.2f s - %.2f s (%.2f s)\n', k, ...
                t_fat(onset_idx(k)), t_fat(offset_idx(k)), dur_k);
    end

    fig_onsets = figure('Name', ['Onsets ' muscle_names{ref_muscle}]);
    plot(t_fat, rms_ref, 'b', 'LineWidth', 1); hold on;
    yline(thr, 'k--', sprintf('Pct %d -> %.1f uV', pct_thr, thr), 'LineWidth', 1);
    for k = 1:n_reps
        xline(t_fat(onset_idx(k)),  'g', 'LineWidth', 1.2);
        xline(t_fat(offset_idx(k)), 'r', 'LineWidth', 1.0);
    end
    xlabel('Time (s)'); ylabel('uV');
    title(sprintf('Onsets (green) and offsets (red) %d reps | Pct %d (%.1f uV)', ...
                  n_reps, pct_thr, thr));
    grid on; hold off;

    fprintf('\n  Hint: lower percentile -> lower threshold -> more reps.\n');
    fprintf('        Higher percentile -> higher threshold -> only clear peaks.\n');
    resp = input('  Adjust? (Enter to accept, or type percentile 0-100): ', 's');
    if isempty(resp)
        close(fig_onsets); break;
    else
        new_pct = str2double(resp);
        if isnan(new_pct) || new_pct < 0 || new_pct > 100
            fprintf('  Invalid value.\n');
        else
            pct_thr = new_pct;
            thr     = prctile(rms_ref, pct_thr);
        end
        close(fig_onsets);
    end
end

% -- MDF per repetition (AR-3, Burg) ----------------------------------------
mdf_reps = nan(n_reps, n_muscles);
t_rep    = nan(n_reps, 1);

fprintf('\nComputing MDF per repetition...\n');
for k = 1:n_reps
    seg_idx  = onset_idx(k) : offset_idx(k);
    t_rep(k) = mean(t_fat(seg_idx)) - t_fat(1);

    for ch = 1:n_muscles
        seg = bp_fat(seg_idx, ch);
        [pxx, f] = pburg(seg, 3, [], Fs);
        mask     = f >= low_cut & f <= high_cut;
        f_m = f(mask); p_m = pxx(mask);
        cum_p = cumsum(p_m);
        mdf_reps(k,ch) = interp1(cum_p, f_m, cum_p(end)/2, 'linear', 'extrap');
    end
end
fprintf('  Done.\n');

% -- Linear regression MDF vs time ------------------------------------------
slopes = nan(1, n_muscles);
r2     = nan(1, n_muscles);

for ch = 1:n_muscles
    y     = mdf_reps(:,ch);
    valid = ~isnan(y);
    if sum(valid) >= 3
        p          = polyfit(t_rep(valid), y(valid), 1);
        slopes(ch) = p(1);
        y_fit      = polyval(p, t_rep(valid));
        ss_res     = sum((y(valid) - y_fit).^2);
        ss_tot     = sum((y(valid) - mean(y(valid))).^2);
        r2(ch)     = 1 - ss_res/ss_tot;
    end
end

% -- Console results --------------------------------------------------------
fprintf('\n--- MDF slopes (Hz/s) ---\n');
fprintf('  %-5s  %8s  %6s\n', 'Musc.', 'Slope', 'R2');
for ch = 1:n_muscles
    fprintf('  %-5s  %+8.4f  %6.3f\n', muscle_names{ch}, slopes(ch), r2(ch));
end

% -- MDF per repetition plot ------------------------------------------------
t_line = linspace(t_rep(1), t_rep(end), 100);
[~, base_name] = fileparts(S.fname);
fig_mdf = figure('Name', ['MDF per repetition ' base_name]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    plot(t_rep, mdf_reps(:,ch), 'bo', 'MarkerFaceColor','b', 'MarkerSize', 4);
    hold on;
    if ~isnan(slopes(ch))
        p_ch = polyfit(t_rep(~isnan(mdf_reps(:,ch))), ...
                       mdf_reps(~isnan(mdf_reps(:,ch)), ch), 1);
        plot(t_line, polyval(p_ch, t_line), 'r-', 'LineWidth', 1.2);
    end
    ylabel('Hz');
    title(sprintf('%s slope: %+.3f Hz/s, R2=%.2f', muscle_names{ch}, slopes(ch), r2(ch)));
    grid on; hold off;
end
xlabel('Relative time (s)');
sgtitle(['MDF per repetition (AR-3 Burg) ' base_name]);

% -- Save -------------------------------------------------------------------
results_dir = fullfile(fpath_mat, 'results');
if ~exist(results_dir, 'dir'), mkdir(results_dir); end

mat_path = fullfile(results_dir, ['mdf3_' base_name '.mat']);
save(mat_path, 'mdf_reps', 't_rep', 'slopes', 'r2', ...
     'muscle_names', 'n_reps', 'pct_thr', 'thr', 'Fs', ...
     'onset_idx', 'offset_idx');
fprintf('Mat saved: %s\n', mat_path);

png_path = fullfile(results_dir, ['mdf3_' base_name '_regression.png']);
fig_mdf.Position = [100 100 1000 900];
print(fig_mdf, png_path, '-dpng', '-r300');
fprintf('PNG saved: %s\n', png_path);
