% =========================================================================
% step2_mdf_v5.m  -  MDF per repetition on the fatigue block
% =========================================================================
% Reads pre_[name].mat generated by step1_preprocess.m.
% Fatigue block already segmented and filtered — no reloading needed.
%
% Method: AR order 3, Burg (pburg), ECR reference + adaptive percentile
%         threshold for onset detection.
%
% v5 changes from v4c (all agreed in Claude-ChatGPT debate, 24-25 Aug 2026):
%   1. Delta MDF in three forms: mean (primary), median (sensitivity),
%      relative % (normalised by basal frequency)
%   2. Removed arbitrary ±2 Hz fatigue tags — values reported as-is
%   3. slope_reliable renamed to slope_r2_flag (informative ONLY —
%      does NOT exclude channels from group-level analysis)
%   4. Theil-Sen robust slope added (NaN filtered before nchoosek)
%   5. Spearman rho added as monotonic-trend descriptor
%   6. RMS active: computed over active windows only (not full block)
%      in µV and %MVC, using S.mvc_uv from step1
%   7. block_duration_s saved as endurance outcome
%   8. Labels corrected: ylabel shows actual channel name, sgtitle
%      reflects ECR/ref channel, output files prefixed mdf5_
%
% Inherited from v3/v4b:
%   - NFFT 1024 (frequency resolution ~2.1 Hz)
%   - Demean before AR fitting
%   - Edge trim 10% each side (middle 80% for spectral analysis)
%   - Adaptive local percentile threshold (decimated, ~0.5s steps)
%   - Manual correction interface (add missing reps)
%   - Verification figure (7-channel onset overlay)
%
% Output: results/mdf5_[name].mat  (see variable list in header below)
%
% Compatibility: MATLAB R2016b+
% =========================================================================
%
% Variables saved in mdf5_[name].mat:
%   onset_idx           [n_reps x 1]   onset sample indices
%   offset_idx          [n_reps x 1]   offset sample indices
%   n_reps              scalar
%   block_duration_s    scalar         fatigue block duration (s)
%   pct_thr             scalar         percentile used
%   thr_vec             [N x 1]        adaptive threshold (full resolution)
%   win_adapt_s         scalar         adaptive window (s)
%   ref_muscle          scalar         reference channel index (7=ECR)
%   mdf_reps            [n_reps x 7]   MDF per rep and channel (Hz)
%   t_rep               [n_reps x 1]   centre time of each rep (s, rel. block)
%   slopes              [1 x 7]        OLS slope (Hz/s)
%   r2                  [1 x 7]        OLS R²
%   slope_r2_flag       [1 x 7]        logical R²>=R2_MIN — informative only
%   slopes_ts           [1 x 7]        Theil-Sen robust slope (Hz/s)
%   slope_spearman_rho  [1 x 7]        Spearman rho (t_rep vs MDF)
%   slope_spearman_p    [1 x 7]        Spearman p-value
%   n_edge              scalar         reps used at each end (min(5,floor(n/4)))
%   mdf_first           [1 x 7]        mean MDF first n_edge reps (Hz)
%   mdf_last            [1 x 7]        mean MDF last  n_edge reps (Hz)
%   delta_mdf_mean      [1 x 7]        mean(last)-mean(first) Hz  [PRIMARY]
%   delta_mdf_med       [1 x 7]        median(last)-median(first) Hz
%   delta_mdf_pct       [1 x 7]        delta relative (%)
%   mdf_low_flag        [1 x 7]        logical mdf_first < MDF_LOW_THR
%   rms_active_uv       [1 x 7]        RMS over active windows (µV)
%   rms_active_mvc      [1 x 7]        RMS active normalised by MVC (%MVC)
%   nfft=1024  trim_pct=0.10  R2_MIN=0.25  MDF_LOW_THR=30  Fs=2148
%   fname_save  condition  muscle_names
% =========================================================================

clear; clc;

% -------------------------------------------------------------------------
% Parameters
% -------------------------------------------------------------------------
Fs          = 2148;
low_cut     = 20;
high_cut    = 450;
nfft        = 1024;      % AR spectrum at 1024 pts -> ~2.1 Hz resolution
trim_pct    = 0.10;      % trim 10% each side of each rep (middle 80%)
R2_MIN      = 0.25;      % R2 threshold for slope_r2_flag (informative only)
MDF_LOW_THR = 30;        % Hz — flag if mdf_first is unexpectedly low

muscle_names = {'AD','LD','PD','UT','BB','TB','ECR'};
n_muscles    = numel(muscle_names);

% -------------------------------------------------------------------------
% Load .mat from step1_preprocess
% -------------------------------------------------------------------------
[fname_mat, fpath_mat] = uigetfile('*.mat', ...
    'Select pre_[name].mat (from step1_preprocess)', 'C:\Users\gzomo\TFG\gente');
if isequal(fname_mat, 0), error('No file selected.'); end

fprintf('Loading %s ...\n', fname_mat);
S = load(fullfile(fpath_mat, fname_mat));

if ~isfield(S, 'fatigue')
    error('Field "fatigue" not found. Use pre_[name].mat from step1_preprocess.m');
end

t_fat  = S.fatigue.t;
bp_fat = S.fatigue.filtered;   % bandpass-filtered [M x 7], in Volts
block_duration_s = t_fat(end) - t_fat(1);

fprintf('  Subject: %s | Condition: %s\n', S.fname, S.condition);
fprintf('  Fatigue block: %.1f - %.1f s  (%.1f s, strategy A: ECR onset/offset + 10%% trim)\n', ...
        t_fat(1), t_fat(end), block_duration_s);

% -------------------------------------------------------------------------
% Linear envelope (LP 8 Hz) for visualisation and onset detection
% -------------------------------------------------------------------------
[b_lp, a_lp] = butter(4, 8/(Fs/2), 'low');
env_fat = zeros(size(bp_fat));
for ch = 1:n_muscles
    env_fat(:,ch) = filtfilt(b_lp, a_lp, abs(bp_fat(:,ch)));
end

% -------------------------------------------------------------------------
% Select reference channel for onset detection
% -------------------------------------------------------------------------
figure('Name', 'Fatigue block envelopes - select reference channel', ...
       'Position', [80 80 1200 700]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    plot(t_fat, env_fat(:,ch)*1e6, 'b', 'LineWidth', 0.7);
    ylabel('uV'); title(muscle_names{ch}); grid on;
    set(gca, 'FontSize', 7);
end
xlabel('Time (s)');
sgtitle('Select reference channel for onset detection (recommended: ECR = 7)');

ref_muscle = input('Reference channel (1=AD 2=LD 3=PD 4=UT 5=BB 6=TB 7=ECR): ');
close;

% Sliding RMS of selected channel (0.5 s window) — in µV
win_rms = round(0.5 * Fs);
rms_ref = sqrt(movmean(bp_fat(:, ref_muscle).^2, win_rms)) * 1e6;   % µV

fprintf('  Reference: %s (ch %d) — sliding RMS 0.5s, adaptive threshold\n', ...
        muscle_names{ref_muscle}, ref_muscle);

% -------------------------------------------------------------------------
% Onset detection: adaptive local percentile threshold
% Decimated computation (~0.5s steps) then interpolated -> avoids O(N^2)
% -------------------------------------------------------------------------
pct_thr     = 15;
win_adapt_s = 20;
win_adapt   = round(win_adapt_s * Fs);
N           = numel(rms_ref);

step       = round(0.5 * Fs);
idx_coarse = (1 : step : N)';
thr_coarse = zeros(size(idx_coarse));
for ii = 1:numel(idx_coarse)
    i1 = max(1, idx_coarse(ii) - floor(win_adapt/2));
    i2 = min(N, idx_coarse(ii) + floor(win_adapt/2));
    thr_coarse(ii) = prctile(rms_ref(i1:i2), pct_thr);
end
thr_vec = interp1(idx_coarse, thr_coarse, (1:N)', 'linear', 'extrap');

col2 = [0.20 0.55 0.85; 0.95 0.60 0.10];   % alternating rep colours (blue/orange)

while true
    above   = rms_ref > thr_vec;
    d_above = diff([0; above; 0]);
    onset_idx  = find(d_above ==  1);
    offset_idx = find(d_above == -1);

    min_dur   = round(1.0 * Fs);
    valid_rep = (offset_idx - onset_idx) >= min_dur;
    onset_idx  = onset_idx(valid_rep);
    offset_idx = offset_idx(valid_rep);
    n_reps     = numel(onset_idx);

    fprintf('\n--- Onset detection (adaptive threshold) ---\n');
    fprintf('  Ref: %s | Percentile: %d | Window: %ds | Reps: %d\n', ...
            muscle_names{ref_muscle}, pct_thr, win_adapt_s, n_reps);
    for k = 1:n_reps
        dur_k = (offset_idx(k) - onset_idx(k)) / Fs;
        fprintf('  Rep %2d: %.2f - %.2f s  (%.2f s)\n', k, ...
                t_fat(onset_idx(k)), t_fat(offset_idx(k)), dur_k);
    end

    fig_on = figure('Name', sprintf('Onsets - %s ref (Pct%d, %ds)', ...
                    muscle_names{ref_muscle}, pct_thr, win_adapt_s), ...
                    'Position', [80 80 1200 420]);
    y_max = max(rms_ref) * 1.08;
    hold on;
    for k = 1:n_reps
        t1 = t_fat(onset_idx(k));  t2 = t_fat(offset_idx(k));
        c  = col2(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max y_max], c, 'FaceAlpha', 0.18, 'EdgeColor', 'none');
        text((t1+t2)/2, y_max*0.97, num2str(k), ...
             'HorizontalAlignment', 'center', 'FontSize', 6.5, 'Color', c*0.6);
    end
    plot(t_fat, rms_ref, 'k', 'LineWidth', 0.9);
    plot(t_fat, thr_vec, 'r--', 'LineWidth', 1.2);
    text(t_fat(round(0.05*N)), thr_vec(round(0.05*N))*1.12, ...
         sprintf('Adaptive Pct%d (%ds window)', pct_thr, win_adapt_s), ...
         'Color', [0.6 0 0], 'FontSize', 8);
    xlabel('Time (s)');
    ylabel(sprintf('%s RMS (uV)', muscle_names{ref_muscle}));
    title(sprintf('%s ref  |  %d reps  |  Adaptive Pct%d (%ds window)', ...
                  muscle_names{ref_muscle}, n_reps, pct_thr, win_adapt_s));
    xlim([t_fat(1) t_fat(end)]); ylim([0 y_max]); grid on; hold off;

    fprintf('\n  Adjust: number -> percentile, w## -> window (s). Enter to accept: ');
    resp = input('', 's');
    if isempty(resp), close(fig_on); break; end
    close(fig_on);
    if resp(1) == 'w'
        new_w = str2double(resp(2:end));
        if ~isnan(new_w) && new_w > 0
            win_adapt_s = new_w;
            win_adapt   = round(win_adapt_s * Fs);
        end
    else
        new_p = str2double(resp);
        if ~isnan(new_p) && new_p > 0 && new_p < 100, pct_thr = new_p; end
    end
    for ii = 1:numel(idx_coarse)
        i1 = max(1, idx_coarse(ii) - floor(win_adapt/2));
        i2 = min(N, idx_coarse(ii) + floor(win_adapt/2));
        thr_coarse(ii) = prctile(rms_ref(i1:i2), pct_thr);
    end
    thr_vec = interp1(idx_coarse, thr_coarse, (1:N)', 'linear', 'extrap');
end

% -------------------------------------------------------------------------
% Manual correction: add missing repetitions
% -------------------------------------------------------------------------
pairs = [onset_idx, offset_idx];

fprintf('\nManual correction - type "add" to insert a rep, or Enter to skip: ');
resp_corr = input('', 's');

while strcmpi(strtrim(resp_corr), 'add')
    fig_corr = figure('Name', 'Manual correction', 'Position', [80 80 1200 420]);
    y_max_c  = max(rms_ref) * 1.08;
    hold on;
    n_curr = size(pairs, 1);
    for k = 1:n_curr
        t1 = t_fat(pairs(k,1));  t2 = t_fat(pairs(k,2));
        c  = col2(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max_c y_max_c], c, 'FaceAlpha', 0.18, 'EdgeColor', 'none');
        text((t1+t2)/2, y_max_c*0.97, num2str(k), ...
             'HorizontalAlignment', 'center', 'FontSize', 6.5, 'Color', c*0.6);
    end
    plot(t_fat, rms_ref, 'k', 'LineWidth', 0.9);
    plot(t_fat, thr_vec, 'r--', 'LineWidth', 1.2);
    xlabel('Time (s)');
    ylabel(sprintf('%s RMS (uV)', muscle_names{ref_muscle}));
    title(sprintf('Click ONSET then OFFSET of missing rep  |  Current: %d reps', n_curr), ...
          'FontSize', 11);
    xlim([t_fat(1) t_fat(end)]); ylim([0 y_max_c]); grid on; hold off;

    fprintf('  Click 2 points: onset then offset\n');
    [x_clicks, ~] = ginput(2);
    x_clicks = sort(x_clicks);
    close(fig_corr);

    [~, new_onset]  = min(abs(t_fat - x_clicks(1)));
    [~, new_offset] = min(abs(t_fat - x_clicks(2)));
    pairs = sortrows([pairs; new_onset, new_offset], 1);
    fprintf('  Added: %.1f - %.1f s  |  Total reps: %d\n', ...
            x_clicks(1), x_clicks(2), size(pairs,1));

    fprintf('  Add another? (type "add" or Enter to finish): ');
    resp_corr = input('', 's');
end

onset_idx  = pairs(:, 1);
offset_idx = pairs(:, 2);
n_reps     = size(pairs, 1);
fprintf('  Final repetition count: %d\n', n_reps);

% -------------------------------------------------------------------------
% Verification: 7-channel overlay
% -------------------------------------------------------------------------
fig_verify = figure('Name', 'Onset verification - all channels', ...
                    'Position', [80 50 1200 820]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    hold on;
    y_max_ch = max(env_fat(:,ch)) * 1e6 * 1.08;
    for k = 1:n_reps
        t1 = t_fat(onset_idx(k));  t2 = t_fat(offset_idx(k));
        c  = col2(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max_ch y_max_ch], c, 'FaceAlpha', 0.20, 'EdgeColor', 'none');
    end
    plot(t_fat, env_fat(:,ch)*1e6, 'k', 'LineWidth', 0.7);
    ylabel('uV', 'FontSize', 7);
    title(muscle_names{ch}, 'FontSize', 8, 'FontWeight', 'bold');
    xlim([t_fat(1) t_fat(end)]); ylim([0 y_max_ch]); grid on; hold off;
    set(gca, 'FontSize', 7);
end
xlabel('Time (s)');
sgtitle(sprintf('Onset verification (%s ref, ch%d) | %d reps | Pct%d (%ds)', ...
                muscle_names{ref_muscle}, ref_muscle, n_reps, pct_thr, win_adapt_s), ...
        'FontSize', 10);

fprintf('\nVerification figure open. Press Enter to continue to MDF computation: ');
input('');
close(fig_verify);

% -------------------------------------------------------------------------
% MDF per repetition (AR-3, Burg, NFFT 1024, trim 10%)
% Strategy A: ECR onset/offset + 10% edge trim (middle 80%)
% -------------------------------------------------------------------------
mdf_reps = nan(n_reps, n_muscles);
t_rep    = nan(n_reps, 1);

fprintf('\nComputing MDF per repetition (AR-3 Burg, NFFT=%d, trim=%.0f%%)...\n', ...
        nfft, trim_pct*100);
for k = 1:n_reps
    seg_full = onset_idx(k) : offset_idx(k);
    n_trim   = round(trim_pct * numel(seg_full));
    seg_idx  = seg_full(n_trim+1 : end-n_trim);   % middle 80%
    t_rep(k) = mean(t_fat(seg_idx)) - t_fat(1);
    for ch = 1:n_muscles
        seg = bp_fat(seg_idx, ch);
        seg = seg - mean(seg);   % demean before AR fitting
        [pxx, f] = pburg(seg, 3, nfft, Fs);
        mask  = f >= low_cut & f <= high_cut;
        f_m   = f(mask);  p_m = pxx(mask);
        cum_p = cumsum(p_m);
        mdf_reps(k,ch) = interp1(cum_p, f_m, cum_p(end)/2, 'linear', 'extrap');
    end
end
fprintf('  Done.\n');

% -------------------------------------------------------------------------
% RMS active: computed over active windows only (V -> µV -> %MVC)
% -------------------------------------------------------------------------
rms_active_uv  = nan(1, n_muscles);
rms_active_mvc = nan(1, n_muscles);

for ch = 1:n_muscles
    segs = [];
    for k = 1:n_reps
        segs = [segs; bp_fat(onset_idx(k):offset_idx(k), ch)];  %#ok<AGROW>
    end
    rms_active_uv(ch) = sqrt(mean(segs.^2)) * 1e6;   % V -> µV
    if isfield(S, 'mvc_uv') && S.mvc_uv(ch) > 0
        rms_active_mvc(ch) = rms_active_uv(ch) / S.mvc_uv(ch) * 100;
    end
end

% -------------------------------------------------------------------------
% OLS slope (Hz/s) per channel
% -------------------------------------------------------------------------
slopes       = nan(1, n_muscles);
r2           = nan(1, n_muscles);
slope_r2_flag = false(1, n_muscles);
% slope_r2_flag is INFORMATIVE ONLY — does NOT exclude from group analysis

for ch = 1:n_muscles
    y     = mdf_reps(:,ch);
    valid = ~isnan(y);
    if sum(valid) >= 3
        p_fit      = polyfit(t_rep(valid), y(valid), 1);
        slopes(ch) = p_fit(1);
        y_fit      = polyval(p_fit, t_rep(valid));
        ss_res     = sum((y(valid) - y_fit).^2);
        ss_tot     = sum((y(valid) - mean(y(valid))).^2);
        r2(ch)     = 1 - ss_res / ss_tot;
        slope_r2_flag(ch) = (r2(ch) >= R2_MIN);
    end
end

% -------------------------------------------------------------------------
% Theil-Sen robust slope (NaN filtered before nchoosek)
% -------------------------------------------------------------------------
slopes_ts = nan(1, n_muscles);

for ch = 1:n_muscles
    y     = mdf_reps(:, ch);
    valid = ~isnan(y) & ~isnan(t_rep);
    yv    = y(valid);
    tv    = t_rep(valid);
    nv    = numel(yv);
    if nv >= 3
        pairs_ts = nchoosek(1:nv, 2);
        s_all    = (yv(pairs_ts(:,2)) - yv(pairs_ts(:,1))) ./ ...
                   (tv(pairs_ts(:,2)) - tv(pairs_ts(:,1)));
        slopes_ts(ch) = median(s_all);
    end
end

% -------------------------------------------------------------------------
% Spearman rho (monotonic trend descriptor)
% -------------------------------------------------------------------------
slope_spearman_rho = nan(1, n_muscles);
slope_spearman_p   = nan(1, n_muscles);

for ch = 1:n_muscles
    y     = mdf_reps(:, ch);
    valid = ~isnan(y) & ~isnan(t_rep);
    if sum(valid) >= 3
        [rho_val, p_val] = corr(t_rep(valid), y(valid), 'Type', 'Spearman');
        slope_spearman_rho(ch) = rho_val;
        slope_spearman_p(ch)   = p_val;
    end
end

% -------------------------------------------------------------------------
% Delta MDF: three variants
% -------------------------------------------------------------------------
n_edge         = min(5, floor(n_reps / 4));
mdf_first      = nan(1, n_muscles);
mdf_last       = nan(1, n_muscles);
delta_mdf_mean = nan(1, n_muscles);
delta_mdf_med  = nan(1, n_muscles);
delta_mdf_pct  = nan(1, n_muscles);
mdf_low_flag   = false(1, n_muscles);

for ch = 1:n_muscles
    y         = mdf_reps(:, ch);
    valid_idx = find(~isnan(y));
    if numel(valid_idx) >= 2 * n_edge
        first_vals    = y(valid_idx(1 : n_edge));
        last_vals     = y(valid_idx(end-n_edge+1 : end));
        mdf_first(ch) = mean(first_vals);
        mdf_last(ch)  = mean(last_vals);
        delta_mdf_mean(ch) = mdf_last(ch) - mdf_first(ch);
        delta_mdf_med(ch)  = median(last_vals) - median(first_vals);
        delta_mdf_pct(ch)  = (mdf_last(ch) - mdf_first(ch)) / mdf_first(ch) * 100;
        mdf_low_flag(ch)   = (mdf_first(ch) < MDF_LOW_THR);
    end
end

% -------------------------------------------------------------------------
% Console output
% -------------------------------------------------------------------------
[~, base_name] = fileparts(S.fname);

fprintf('\n=== v5 results: %s | %s | %d reps ===\n', base_name, S.condition, n_reps);
fprintf('Block duration: %.1f s\n\n', block_duration_s);

fprintf('--- Slope metrics (OLS, Theil-Sen, Spearman) ---\n');
fprintf('  Note: slope_r2_flag is informative only — does NOT exclude from analysis.\n');
fprintf('  %-5s  %9s  %5s  %4s  %12s  %7s  %6s\n', ...
        'Musc.', 'OLS(Hz/s)', 'R2', 'Flag', 'TheilS(Hz/s)', 'SpRho', 'SpP');
for ch = 1:n_muscles
    flag_str = '   ';
    if slope_r2_flag(ch), flag_str = 'OK '; else, flag_str = '---'; end
    fprintf('  %-5s  %+9.4f  %5.3f  %s   %+12.4f  %+7.3f  %6.3f\n', ...
            muscle_names{ch}, slopes(ch), r2(ch), flag_str, ...
            slopes_ts(ch), slope_spearman_rho(ch), slope_spearman_p(ch));
end

fprintf('\n--- Delta MDF: first %d vs last %d reps ---\n', n_edge, n_edge);
fprintf('  %-5s  %9s  %8s  %9s  %8s  %8s  %s\n', ...
        'Musc.', 'First(Hz)', 'Last(Hz)', 'Mean(Hz)', 'Med(Hz)', 'Pct(%)', 'LowFlag');
for ch = 1:n_muscles
    if ~isnan(delta_mdf_mean(ch))
        low_str = ''; if mdf_low_flag(ch), low_str = '*** LOW'; end
        fprintf('  %-5s  %9.2f  %8.2f  %+9.2f  %+8.2f  %+8.1f  %s\n', ...
                muscle_names{ch}, mdf_first(ch), mdf_last(ch), ...
                delta_mdf_mean(ch), delta_mdf_med(ch), delta_mdf_pct(ch), low_str);
    else
        fprintf('  %-5s  insufficient reps (need >= %d)\n', muscle_names{ch}, 2*n_edge);
    end
end

fprintf('\n--- RMS active (over active windows only) ---\n');
fprintf('  %-5s  %10s  %10s\n', 'Musc.', 'RMS(uV)', 'RMS(%MVC)');
for ch = 1:n_muscles
    if ~isnan(rms_active_uv(ch))
        mvc_str = '  n/a';
        if ~isnan(rms_active_mvc(ch)), mvc_str = sprintf('%10.1f', rms_active_mvc(ch)); end
        fprintf('  %-5s  %10.2f  %s\n', muscle_names{ch}, rms_active_uv(ch), mvc_str);
    end
end

% -------------------------------------------------------------------------
% MDF per repetition figure
% -------------------------------------------------------------------------
t_line = linspace(t_rep(1), t_rep(end), 100);
fig_mdf = figure('Name', ['MDF per repetition ' base_name], ...
                 'Position', [100 50 1000 900]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    hold on;
    plot(t_rep, mdf_reps(:,ch), 'bo', 'MarkerFaceColor','b', 'MarkerSize', 4);
    if ~isnan(slopes(ch))
        p_ch = polyfit(t_rep(~isnan(mdf_reps(:,ch))), ...
                       mdf_reps(~isnan(mdf_reps(:,ch)), ch), 1);
        plot(t_line, polyval(p_ch, t_line), 'r-', 'LineWidth', 1.2);
    end
    ylabel('Hz');
    if ~isnan(slopes(ch))
        title(sprintf('%s  OLS:%+.3f Hz/s R2=%.2f | TheilS:%+.3f | Δmean:%+.1f Hz (%.1f%%)', ...
              muscle_names{ch}, slopes(ch), r2(ch), slopes_ts(ch), ...
              delta_mdf_mean(ch), delta_mdf_pct(ch)), 'FontSize', 7);
    else
        title(muscle_names{ch});
    end
    grid on; hold off;
end
xlabel('Relative time (s)');
sgtitle(sprintf('MDF per rep — AR-3 Burg — %s ref (ch%d) — %s  %s', ...
                muscle_names{ref_muscle}, ref_muscle, base_name, S.condition), ...
        'FontSize', 9);

% -------------------------------------------------------------------------
% Save
% -------------------------------------------------------------------------
results_dir = fullfile(fpath_mat, 'results');
if ~exist(results_dir, 'dir'), mkdir(results_dir); end

mat_path   = fullfile(results_dir, ['mdf5_' base_name '.mat']);
png_path   = fullfile(results_dir, ['mdf5_' base_name '_regression.png']);
fname_save = S.fname;
condition  = S.condition;

save(mat_path, ...
     'onset_idx', 'offset_idx', 'n_reps', 'block_duration_s', ...
     'pct_thr', 'thr_vec', 'win_adapt_s', 'ref_muscle', ...
     'mdf_reps', 't_rep', ...
     'slopes', 'r2', 'slope_r2_flag', ...
     'slopes_ts', ...
     'slope_spearman_rho', 'slope_spearman_p', ...
     'n_edge', 'mdf_first', 'mdf_last', ...
     'delta_mdf_mean', 'delta_mdf_med', 'delta_mdf_pct', 'mdf_low_flag', ...
     'rms_active_uv', 'rms_active_mvc', ...
     'nfft', 'trim_pct', 'R2_MIN', 'MDF_LOW_THR', 'Fs', 'muscle_names', ...
     'fname_save', 'condition');
fprintf('\nMat saved: %s\n', mat_path);

fig_mdf.Position = [100 100 1000 900];
print(fig_mdf, png_path, '-dpng', '-r300');
fprintf('PNG saved: %s\n', png_path);
