% =========================================================================
% step2_mdf_v4b.m MDF per repetition on the fatigue block
% =========================================================================
% Reads the .mat file generated by step1_preprocess.m (pre_[name].mat).
% The fatigue block is already segmented and filtered no reloading
% or re-selection needed.
%
% Method: AR order 3, Burg's method (pburg), onset detection by percentile.
%
% v4b variant: single reference channel + adaptive threshold.
%   - User selects one reference channel (e.g. ECR for consistent grip signal)
%   - Adaptive percentile threshold on that channel's sliding RMS
%     (same 20s window approach as v4 — handles amplitude drift along block)
%   - For comparison with v4 (global signal) to decide which onset strategy is better.
%
% Inherited from v3:
%   - NFFT 1024 for pburg (frequency resolution ~2.1 Hz)
%   - Segment demeaned before AR fitting
%   - Edge trimming 10%: middle 80% of each repetition for spectral analysis
%   - R2 reliability flag: slopes with R2 < R2_MIN flagged as unreliable
%
% Output results/mdf4_[name].mat:
%   .mdf_reps       [n_reps x 7]  MDF per repetition and channel (Hz)
%   .t_rep          [n_reps x 1]  centre time of each rep (s, relative to block)
%   .slopes         [1 x 7]       linear regression slope (Hz/s)
%   .r2             [1 x 7]       coefficient of determination
%   .slope_reliable [1 x 7]       logical: R2 >= R2_MIN
%   .pct_thr        percentile used as onset threshold
%   .thr            threshold value in uV
%   .muscle_names
%   .n_reps
%   .fname
%   .condition
%
% Compatibility: MATLAB R2016b+
% =========================================================================

clear; clc;

% -- Parameters -------------------------------------------------------------
Fs       = 2148;
low_cut  = 20;
high_cut = 450;
nfft     = 1024;   % AR spectrum evaluated at 1024 points -> ~2.1 Hz resolution
trim_pct = 0.10;   % fraction to trim from each edge of every repetition (10%)
R2_MIN   = 0.25;   % minimum R2 for a slope to be flagged as reliable

muscle_names = {'AD','LD','PD','UT','BB','TB','ECR'};
n_muscles    = numel(muscle_names);

% -- Load .mat from step1_preprocess ----------------------------------------
[fname_mat, fpath_mat] = uigetfile('*.mat', 'Select pre_[name].mat (from step1_preprocess)', 'C:\Users\gzomo\TFG\gente');
if isequal(fname_mat, 0), error('No file selected.'); end

fprintf('Loading %s ...\n', fname_mat);
S = load(fullfile(fpath_mat, fname_mat));

% Check that the fatigue block is present
if ~isfield(S, 'fatigue')
    error('The .mat does not contain the "fatigue" field. Make sure to use the output of step1_preprocess.m');
end

t_fat  = S.fatigue.t;
bp_fat = S.fatigue.filtered;   % already filtered [M x 7]
fprintf('  Subject: %s | Condition: %s\n', S.fname, S.condition);
fprintf('  Fatigue block: %.1f - %.1f s (%.1f s)\n', ...
        t_fat(1), t_fat(end), t_fat(end)-t_fat(1));

% -- Single reference channel for onset detection ---------------------------
% Show all envelopes so user can pick the best reference channel
[b_lp, a_lp] = butter(4, 8/(Fs/2), 'low');
env_fat = zeros(size(bp_fat));
for ch = 1:n_muscles
    env_fat(:,ch) = filtfilt(b_lp, a_lp, abs(bp_fat(:,ch)));
end

figure('Name', 'Fatigue block envelopes - select reference channel', ...
       'Position', [80 80 1200 700]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    plot(t_fat, env_fat(:,ch)*1e6, 'b', 'LineWidth', 0.7);
    ylabel('uV'); title(muscle_names{ch}); grid on;
    set(gca, 'FontSize', 7);
end
xlabel('Time (s)');
sgtitle('Select reference channel for onset detection');

ref_muscle = input('Reference channel (1=AD 2=LD 3=PD 4=UT 5=BB 6=TB 7=ECR): ');
close;

% Sliding RMS of selected channel (0.5s window)
win_rms = round(0.5 * Fs);
rms_ref = sqrt(movmean(bp_fat(:, ref_muscle).^2, win_rms)) * 1e6;   % uV

fprintf('  Onset detection: single channel %s (sliding RMS 0.5s, adaptive threshold)\n', ...
        muscle_names{ref_muscle});

% -- Onset detection: adaptive local percentile threshold ------------------
% Threshold computed in a sliding window (win_adapt_s seconds) so it follows
% local amplitude changes (fatigue lowers EMG amplitude in later reps).
pct_thr      = 15;
win_adapt_s  = 20;   % local window duration (s)
win_adapt    = round(win_adapt_s * Fs);
N            = numel(rms_ref);

% Compute adaptive threshold: evaluate prctile every 0.5s then interpolate
% (avoids O(N^2) loop over all samples)
step        = round(0.5 * Fs);
idx_coarse  = (1 : step : N)';
thr_coarse  = zeros(size(idx_coarse));
for ii = 1:numel(idx_coarse)
    i1 = max(1, idx_coarse(ii) - floor(win_adapt/2));
    i2 = min(N, idx_coarse(ii) + floor(win_adapt/2));
    thr_coarse(ii) = prctile(rms_ref(i1:i2), pct_thr);
end
thr_vec = interp1(idx_coarse, thr_coarse, (1:N)', 'linear', 'extrap');

while true
    above   = rms_ref > thr_vec;
    d_above = diff([0; above; 0]);
    onset_idx  = find(d_above ==  1);
    offset_idx = find(d_above == -1);

    min_dur    = round(1.0 * Fs);
    valid      = (offset_idx - onset_idx) >= min_dur;
    onset_idx  = onset_idx(valid);
    offset_idx = offset_idx(valid);
    n_reps     = numel(onset_idx);

    fprintf('\n--- Repetition detection (adaptive threshold) ---\n');
    fprintf('  Percentile: %d | Window: %ds | Repetitions: %d\n', pct_thr, win_adapt_s, n_reps);
    for k = 1:n_reps
        dur_k = (offset_idx(k) - onset_idx(k)) / Fs;
        fprintf('  Rep %2d: %.2f s - %.2f s (%.2f s)\n', k, ...
                t_fat(onset_idx(k)), t_fat(offset_idx(k)), dur_k);
    end

    fig_onsets = figure('Name', ['Onsets - ' muscle_names{ref_muscle} ' (adaptive)'], ...
                        'Position', [80 80 1200 420]);
    y_max = max(rms_ref) * 1.08;
    hold on;
    colors_rep = [0.20 0.55 0.85; 0.95 0.60 0.10];
    for k = 1:n_reps
        t1 = t_fat(onset_idx(k));
        t2 = t_fat(offset_idx(k));
        c  = colors_rep(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max y_max], c, ...
              'FaceAlpha', 0.18, 'EdgeColor', 'none');
        text((t1+t2)/2, y_max*0.97, num2str(k), ...
             'HorizontalAlignment', 'center', 'FontSize', 6.5, 'Color', c*0.6);
    end
    plot(t_fat, rms_ref, 'k', 'LineWidth', 0.9);
    plot(t_fat, thr_vec, 'r--', 'LineWidth', 1.2);   % adaptive threshold curve
    text(t_fat(round(0.05*N)), thr_vec(round(0.05*N))*1.12, ...
         sprintf('Adaptive Pct%d (%ds window)', pct_thr, win_adapt_s), ...
         'Color', [0.6 0 0], 'FontSize', 8);
    xlabel('Time (s)'); ylabel('Global activity (norm.)');
    title(sprintf('%s  |  %d reps  |  Adaptive Pct%d (%ds window)', ...
                  muscle_names{ref_muscle}, n_reps, pct_thr, win_adapt_s));
    xlim([t_fat(1) t_fat(end)]); ylim([0 y_max]);
    grid on; hold off;

    fprintf('\n  Adjust percentile (p) or window in seconds (w)?\n');
    fprintf('  Examples: "12" changes percentile, "w30" changes window to 30s.\n');
    fprintf('  Press Enter to accept: ');
    resp = input('', 's');
    if isempty(resp)
        close(fig_onsets); break;
    end
    close(fig_onsets);
    if resp(1) == 'w'
        new_w = str2double(resp(2:end));
        if ~isnan(new_w) && new_w > 0
            win_adapt_s = new_w;
            win_adapt   = round(win_adapt_s * Fs);
        end
    else
        new_pct = str2double(resp);
        if ~isnan(new_pct) && new_pct > 0 && new_pct < 100
            pct_thr = new_pct;
        end
    end
    % Recompute adaptive threshold (decimated)
    for ii = 1:numel(idx_coarse)
        i1 = max(1, idx_coarse(ii) - floor(win_adapt/2));
        i2 = min(N, idx_coarse(ii) + floor(win_adapt/2));
        thr_coarse(ii) = prctile(rms_ref(i1:i2), pct_thr);
    end
    thr_vec = interp1(idx_coarse, thr_coarse, (1:N)', 'linear', 'extrap');
end

% -- Manual correction: add missing repetitions ----------------------------
% Manage as [onset, offset] pairs so insertion keeps them paired
pairs = [onset_idx, offset_idx];   % [n_reps x 2]

fprintf('\nManual correction - add missing repetitions?\n');
fprintf('  Type "add" to add one, or press Enter to skip: ');
resp_corr = input('', 's');

while strcmpi(strtrim(resp_corr), 'add')
    % Show current detection
    fig_corr = figure('Name', 'Manual correction', 'Position', [80 80 1200 420]);
    y_max_c  = max(rms_ref) * 1.08;
    hold on;
    colors_rep = [0.20 0.55 0.85; 0.95 0.60 0.10];
    n_curr = size(pairs, 1);
    for k = 1:n_curr
        t1 = t_fat(pairs(k,1));
        t2 = t_fat(pairs(k,2));
        c  = colors_rep(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max_c y_max_c], c, ...
              'FaceAlpha', 0.18, 'EdgeColor', 'none');
        text((t1+t2)/2, y_max_c*0.97, num2str(k), ...
             'HorizontalAlignment', 'center', 'FontSize', 6.5, 'Color', c*0.6);
    end
    plot(t_fat, rms_ref, 'k', 'LineWidth', 0.9);
    plot(t_fat, thr_vec, 'r--', 'LineWidth', 1.2);
    xlabel('Time (s)'); ylabel('Global activity (norm.)');
    title(sprintf('Click ONSET then OFFSET of missing rep  |  Current: %d reps', n_curr), ...
          'FontSize', 11);
    xlim([t_fat(1) t_fat(end)]); ylim([0 y_max_c]);
    grid on; hold off;

    fprintf('  Click 2 points: onset then offset of the missing repetition\n');
    [x_clicks, ~] = ginput(2);
    x_clicks = sort(x_clicks);
    close(fig_corr);

    [~, new_onset]  = min(abs(t_fat - x_clicks(1)));
    [~, new_offset] = min(abs(t_fat - x_clicks(2)));

    pairs = sortrows([pairs; new_onset, new_offset], 1);   % insert + re-sort by onset

    fprintf('  Added: %.1f - %.1f s  |  Total reps: %d\n', ...
            x_clicks(1), x_clicks(2), size(pairs,1));

    fprintf('  Add another? (type "add" or press Enter to finish): ');
    resp_corr = input('', 's');
end

% Unpack corrected pairs
onset_idx  = pairs(:, 1);
offset_idx = pairs(:, 2);
n_reps     = size(pairs, 1);
fprintf('  Final repetition count: %d\n', n_reps);

% -- Verification: all 7 envelopes with detected onset/offset bands ---------
fig_verify = figure('Name', 'Onset verification - all channels', ...
                    'Position', [80 50 1200 820]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    hold on;
    % Shade each repetition
    colors_rep = [0.20 0.55 0.85; 0.95 0.60 0.10];
    y_max_ch = max(env_fat(:,ch)) * 1e6 * 1.08;
    for k = 1:n_reps
        t1 = t_fat(onset_idx(k));
        t2 = t_fat(offset_idx(k));
        c  = colors_rep(mod(k,2)+1, :);
        patch([t1 t2 t2 t1], [0 0 y_max_ch y_max_ch], c, ...
              'FaceAlpha', 0.20, 'EdgeColor', 'none');
    end
    plot(t_fat, env_fat(:,ch)*1e6, 'k', 'LineWidth', 0.7);
    ylabel('uV', 'FontSize', 7);
    title(muscle_names{ch}, 'FontSize', 8, 'FontWeight', 'bold');
    xlim([t_fat(1) t_fat(end)]);
    ylim([0 y_max_ch]);
    grid on; hold off;
    set(gca, 'FontSize', 7);
end
xlabel('Time (s)');
sgtitle(sprintf('Onset verification (%s ref) | %d reps | Adaptive Pct%d (%ds)', ...
                muscle_names{ref_muscle}, n_reps, pct_thr, win_adapt_s), ...
        'FontSize', 10);

fprintf('\nVerification figure open. Press Enter to continue to MDF computation: ');
input('');
close(fig_verify);

% -- MDF per repetition (AR-3, Burg) ----------------------------------------
mdf_reps = nan(n_reps, n_muscles);
t_rep    = nan(n_reps, 1);

fprintf('\nComputing MDF per repetition...\n');
for k = 1:n_reps
    % Full segment indices
    seg_full = onset_idx(k) : offset_idx(k);

    % Trim edges to exclude movement onset/offset transients (middle 80%)
    n_trim  = round(trim_pct * numel(seg_full));
    seg_idx = seg_full(n_trim+1 : end-n_trim);

    t_rep(k) = mean(t_fat(seg_idx)) - t_fat(1);

    for ch = 1:n_muscles
        seg = bp_fat(seg_idx, ch);
        seg = seg - mean(seg);   % demean: remove residual drift before AR fitting
        [pxx, f] = pburg(seg, 3, nfft, Fs);
        mask     = f >= low_cut & f <= high_cut;
        f_m = f(mask); p_m = pxx(mask);
        cum_p = cumsum(p_m);
        mdf_reps(k,ch) = interp1(cum_p, f_m, cum_p(end)/2, 'linear', 'extrap');
    end
end
fprintf('  Done.\n');

% -- Linear regression MDF vs time ------------------------------------------
slopes         = nan(1, n_muscles);
r2             = nan(1, n_muscles);
slope_reliable = false(1, n_muscles);

for ch = 1:n_muscles
    y     = mdf_reps(:,ch);
    valid = ~isnan(y);
    if sum(valid) >= 3
        p          = polyfit(t_rep(valid), y(valid), 1);
        slopes(ch) = p(1);
        y_fit      = polyval(p, t_rep(valid));
        ss_res     = sum((y(valid) - y_fit).^2);
        ss_tot     = sum((y(valid) - mean(y(valid))).^2);
        r2(ch)     = 1 - ss_res/ss_tot;
        slope_reliable(ch) = (r2(ch) >= R2_MIN);
    end
end

% -- Console results: slope -------------------------------------------------
fprintf('\n--- MDF slopes (Hz/s) ---\n');
fprintf('  %-5s  %8s  %6s  %s\n', 'Musc.', 'Slope', 'R2', 'Reliable');
for ch = 1:n_muscles
    rel_str = 'YES';
    if ~slope_reliable(ch), rel_str = '*** NO (R2 low)'; end
    fprintf('  %-5s  %+8.4f  %6.3f  %s\n', muscle_names{ch}, slopes(ch), r2(ch), rel_str);
end
if any(~slope_reliable)
    fprintf('\n  Warning: %d channel(s) flagged unreliable (R2 < %.2f).\n', ...
            sum(~slope_reliable), R2_MIN);
    fprintf('  These will be excluded from group-level fatigue analysis.\n');
end


% -- MDF per repetition plot ------------------------------------------------
t_line = linspace(t_rep(1), t_rep(end), 100);
[~, base_name] = fileparts(S.fname);
fig_mdf = figure('Name', ['MDF per repetition ' base_name]);
for ch = 1:n_muscles
    subplot(n_muscles, 1, ch);
    plot(t_rep, mdf_reps(:,ch), 'bo', 'MarkerFaceColor','b', 'MarkerSize', 4);
    hold on;
    if ~isnan(slopes(ch))
        p_ch = polyfit(t_rep(~isnan(mdf_reps(:,ch))), ...
                       mdf_reps(~isnan(mdf_reps(:,ch)), ch), 1);
        plot(t_line, polyval(p_ch, t_line), 'r-', 'LineWidth', 1.2);
    end
    ylabel('Hz');
    title(sprintf('%s slope: %+.3f Hz/s, R2=%.2f', muscle_names{ch}, slopes(ch), r2(ch)));
    grid on; hold off;
end
xlabel('Relative time (s)');
sgtitle(['MDF per repetition - AR-3 Burg - global onset - ' base_name]);

% -- Save -------------------------------------------------------------------
results_dir = fullfile(fpath_mat, 'results');
if ~exist(results_dir, 'dir'), mkdir(results_dir); end

mat_path = fullfile(results_dir, ['mdf4_' base_name '.mat']);
fname_save = S.fname;
condition  = S.condition;
save(mat_path, 'mdf_reps', 't_rep', 'slopes', 'r2', 'slope_reliable', ...
     'muscle_names', 'n_reps', 'pct_thr', 'thr_vec', 'Fs', ...
     'onset_idx', 'offset_idx', 'nfft', 'trim_pct', 'R2_MIN', ...
     'fname_save', 'condition', 'ref_muscle', 'win_adapt_s');
fprintf('Mat saved: %s\n', mat_path);

png_path = fullfile(results_dir, ['mdf4_' base_name '_regression.png']);
fig_mdf.Position = [100 100 1000 900];
print(fig_mdf, png_path, '-dpng', '-r300');
fprintf('PNG saved: %s\n', png_path);
